project_id = "aldwmdfveivkfxxvfoua"

[functions.ingest-envios]
verify_jwt = false

[functions.update-tracking]
verify_jwt = false

[functions.link-sos-to-carga]
verify_jwt = false

[functions.upsert-carga]
verify_jwt = false

[functions.cleanup-auth-attempts]
verify_jwt = false

[functions.bulk-update-cargas]
verify_jwt = false

[functions.query-envios]
verify_jwt = false

[functions.update-envio-data]
verify_jwt = false

[functions.export-data]
verify_jwt = false
