project_id = "aldwmdfveivkfxxvfoua"

[functions.ingest-envios]
verify_jwt = false

[functions.update-tracking]
verify_jwt = false

[functions.create-carga]
verify_jwt = false

[functions.update-carga]
verify_jwt = false
