project_id = "aldwmdfveivkfxxvfoua"

[functions.ingest-envios]
verify_jwt = false

[functions.update-tracking]
verify_jwt = false

[functions.link-sos-to-carga]
verify_jwt = false

[functions.upsert-carga]
verify_jwt = false
